### ISSUE TITLE
diff and migrate not available in the console application

### ISSUE THREAD

**Issue by netbrothers-tr** [EmeryEx/zpropel#1]
Hi and thank you first of all for this module! We make extensive use of it. Is there any reason why the commands `diff` and `migrate` aren't allowed in the [route of the genAction](https://github.com/MarshallHouse/zpropel/blob/ab24e50d9307595270d6a2ae3b7b334a21f7a3f9/Module.php#L57)? Thanks in advance for your answer!

**Comment by EmeryEx** [comment]
Well the routes programmed in the module's routing config are just basic. You can run the Propel bin file directly with any of its real parameters. It was too complex to convert to ZF2 routes at the time of writing this module and i no longer use Propel myself so the project is dead. Perhaps you should fork it and edit it to make it better.

-----Original Message-----

**Comment by netbrothers-tr** [comment]
Okay, good to know and thanks for the reply!
